# Generated by Django 3.2.5 on 2021-07-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
