# Generated by Django 3.2.5 on 2021-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
