# Generated by Django 3.2.5 on 2021-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_state_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbvr',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
