# Generated by Django 3.2.5 on 2021-07-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_state_abbvr'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
