# Generated by Django 3.2.5 on 2021-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_state_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
