# Generated by Django 3.2.5 on 2021-07-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210708_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
