# Generated by Django 3.2.5 on 2021-07-11 00:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
