# Generated by Django 3.2.5 on 2021-07-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20210711_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
