# Generated by Django 3.2.5 on 2021-07-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
