# Generated by Django 3.2.5 on 2021-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
